### ISSUE TITLE
how use custom formula in angular 

### ISSUE THREAD

**Issue by gbelmm** [paulhodel/jexcel-with-angular#1]
example:

`var COLORIZE = function(v) {
    v = '<span style="color:' + v + '">' + v.toUpperCase() + '</span>';
    return v;
}

var data1 = [
    [ 'red', '=COLORIZE(A1)' ],
    [ 'green', '=COLORIZE(A2)' ],
    [ 'blue', '=COLORIZE(A3)' ],
];

jexcel(document.getElementById('spreadsheet1'), {
    data:data1,
    columns: [
        { type: 'text', width:'300' },
        { type: 'text', width:'200' },
    ]
});`

**Comment by deftdawg** [comment]
@gbelmm I think you're trying to ask how to use the COLORIZE example right?

You'll want to use `` ``` ``  to format code on github (or just use the code `<>` icon in the composer).  Also your code is missing the `style`  that actually changes the colour, so yours only upper cases it.

I'm by no means an Angular expert, so there might be better ways to do it, but this solution worked for me:

Create a file `src/assets/js/custom.js` with the following:
```javascript
function COLORIZE(v) {
    v = '<span style="color:' + v + '">' + v.toUpperCase() + '</span>';
    return v;
}
```

At the end of `src/app/jexcel-spreadsheet/jexcel-spreadsheet.component.ts` add `ngAfterViewChecked` with the following to load the javascript
```typescript
  ngAfterViewChecked() {
    var s = document.createElement("script");
    s.type = "text/javascript";
    s.src = "../../assets/js/custom.js";
    this.spreadsheet.nativeElement.appendChild(s);
  }

}
```

**Comment by deftdawg** [comment]
@gbelmm kindly close the issue by clicking the `Close Issue` button in the comment box, if you're good wth my suggestion.

**Comment by paulhodel** [comment]
In the end of the day, those methods should be available in the global scope.

**Comment by gbelmm** [comment]
it is possible to pass the custom function by parameters inside jexcel, in angular, vue, react it is complicated to leave the global variable, I have tried but it does not work?
