### ISSUE TITLE
Calendar keyboard input broken

### ISSUE THREAD

**Issue by deftdawg** [paulhodel/jexcel-with-angular#4]
https://codesandbox.io/s/jexcel-and-angular-powh0?file=/src/app/app.component.ts

When a calendar type is set with `readonly:0`, pressing any key will double the keystrokes in the input field.   `2` becomes `22`.   Maybe two functions binding to the same keypress events?

Another thing I noticed is when editing a calendar field in this way, paste cannot be used.

Using the picker works and pasting over a date when the field is not being edited does work okay.

**Comment by deftdawg** [comment]
Doesn't not happen with a very basic JSuites example...  That suggests the key duplication is either happening at the JExcel or Angular levels... 

Basic example - no problem:
```html
<html>
<script src="https://bossanova.uk/jsuites/v3/jsuites.js"></script>
<script src="https://bossanova.uk/jsuites/v3/jsuites.webcomponents.js"></script>
<link rel="stylesheet" href="https://bossanova.uk/jsuites/v3/jsuites.css" type="text/css" />

<input id='calendar'>

<script>
var myCalendar = jSuites.calendar(document.getElementById('calendar'),{
    format: 'YYYY-MM-DD', readonly: 0
});

</script>
</html>
```

**Comment by paulhodel** [comment]
The example you sent seems to work as expected. Sometimes a second number can be included automatically in the date.
For example:
I am entering:
2020-   

Them I press a number 2. There is no month starting with month two, so the only possibility is February and it will enter 02.
2020-02-

Them I press a number 3. It will include only the three, since the possibilities for the day are: 03, 30, 31 (because it has more them one option it will wait for the next charater.

Regards,

**Comment by deftdawg** [comment]
Ok thanks your explanation makes some sense as to why that would happen.  

I guess in my case it's doing something out of whack, making it difficult to impossible to enter certain takes:
<img src="https://user-images.githubusercontent.com/4991612/87225556-f77fa780-c35b-11ea-95c2-4f82874d2a38.gif" width="250" height="400">

Might be a bit more convenient with a tab-completable placeholder, i.e. user could either type something over or hit tab to accept the prediction.

**Comment by paulhodel** [comment]
I guess this is related to the mask you are using. The default would be
YYYY-MM-DD, maybe you are expecting a different format?

Regards,

**Comment by paulhodel** [comment]
Force a format and I this will be fixed.

           ```
 {
                type:'calendar',
                title:'From',
                options: { format:'YYYY-MM-DD', readonly: false },
                width:'150px',
            },
```

**Comment by deftdawg** [comment]
The column definition is:
```javascript
            { title: 'Date Of Birth\n(Required)', type: 'calendar', width: 110, 
              options: { 
                format:'YYYY-MM-DD', 
                placeholder: 'YYYY-MM-DD',
                readonly: false,
           }
```

I noticed there are some `two()` functions in JSuites Calendar, they don't be the ones causing this from what I can tell (I commented them out).   I'll see if I can find something like that in JExcel.js.

Anyway thank you for replying...    I'll comment if I figure it out.  🍻

**Comment by paulhodel** [comment]
This is caused by the mask. I have tested your example, it seems to be
working fine for me.

Regards,

**Comment by deftdawg** [comment]
The event is not being consumed entirely / stopped by `e.preventDefault();` within Jsuite's `obj.apply` function, rather a `stopImmediatePropagation()` is required to prevent `zone.js` from duplicating the input through `globalZoneAwareCallback` function.  

```javascript
    obj.apply = function(e) {
        if (e.target && ! e.target.getAttribute('readonly')) {
            var mask = e.target.getAttribute('data-mask');
            if (mask) {
...
                // New input
                if (e.keyCode > 46) {
                    obj.process(obj.fromKeyCode(e));
                    // Prevent default
                    e.preventDefault();
                    e.stopImmediatePropagation(); // Stops input duplication
                }
```

This is the block within `globalZoneAwareCallback` in `zone-evergreen.js` that gives the trouble
```javascript
                        if (event && event[IMMEDIATE_PROPAGATION_SYMBOL] === true) {
                            break;
                        }
                        invokeTask(copyTasks[i], target, event);
```

Googling it I found this which kind of talks about [preventDefault vs stopPropgation vs stopImmediatePropagation](https://codeplanetio.wordpress.com/2015/05/19/preventdefault-vs-stoppropagation-vs-stopimmediatepropagation/) ...

**Comment by deftdawg** [comment]
It seems both `e.preventDefault()` and `e.stopImmediatePropagation()` required...  When I remove either, duplicates keystrokes appear again w/ Angular (zone.js is a dep for Angular).
